export const GET_CARDS_STARTED = 'GET_CARDS_STARTED'
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS'
export const GET_CARDS_FAILURE = 'GET_CARDS_FAILURE'

export const GET_CARDS_BY_ID_STARTED = 'GET_CARDS_BY_ID_STARTED'
export const GET_CARDS_BY_ID_SUCCESS = 'GET_CARDS_BY_ID_SUCCESS'
export const GET_CARDS_BY_ID_FAILURE = 'GET_CARDS_BY_ID_FAILURE'

export const SET_CARDS_BY_ID_STARTED = 'SET_CARDS_BY_ID_STARTED'
export const SET_CARDS_BY_ID_SUCCESS = 'SET_CARDS_BY_ID_SUCCESS'
export const SET_CARDS_BY_ID_FAILURE = 'SET_CARDS_BY_ID_FAILURE'
